"""add role column to user table

Revision ID: c7dce543ea50
Revises: 47844dfc0d3a
Create Date: 2026-08-13 21:18:40.440764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7dce543ea50'
down_revision: Union[str, Sequence[str], None] = '47844dfc0d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first so existing rows won't violate NOT NULL
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # Populate existing rows with a default role value
    op.execute("UPDATE users SET role='user' WHERE role IS NULL")
    # Now make the column non-nullable
    op.alter_column('users', 'role', existing_type=sa.String(length=50), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
